# Generated by Django 3.1.5 on 2021-01-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=85, unique=True),
        ),
    ]
