# Generated by Django 3.1.5 on 2021-01-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='location',
        ),
        migrations.AddField(
            model_name='job',
            name='WorkType',
            field=models.CharField(choices=[('N', 'Not Specified'), ('F', 'Full Time'), ('P', 'Part Time')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(default='Not Specified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='summary',
            field=models.TextField(default='Not Specified'),
            preserve_default=False,
        ),
    ]
