# Generated by Django 3.1.5 on 2021-01-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0002_auto_20210130_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=30, unique=True),
        ),
    ]
