# Generated by Django 3.1.5 on 2021-01-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0002_auto_20210129_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='company_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='company_size',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='founded',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='website',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
