# Generated by Django 3.1.5 on 2021-01-30 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0003_job_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='hireapp.company'),
            preserve_default=False,
        ),
    ]
