# Generated by Django 3.1.5 on 2021-01-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0005_auto_20210130_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='WorkType',
            new_name='work_type',
        ),
        migrations.AddField(
            model_name='job',
            name='rate_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='rate_unit',
            field=models.CharField(choices=[('N', 'Not Specified'), ('H', 'Hourly'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='company',
            name='street',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
