# Generated by Django 3.1.5 on 2021-01-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0007_auto_20210130_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Undefined Profile'), (2, 'Company Contact'), (3, 'Future Employee')], null=True),
        ),
    ]
