# Generated by Django 3.1.5 on 2021-01-30 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0009_auto_20210130_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='role',
            new_name='profile_type',
        ),
    ]
