# Generated by Django 3.1.5 on 2021-01-30 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0012_auto_20210130_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='HiringManager',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='hireapp.hiringmanager'),
            preserve_default=False,
        ),
    ]
