# Generated by Django 3.1.5 on 2021-01-30 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0013_rating_hiringmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='HiringManager',
            new_name='hiring_manager',
        ),
    ]
