# Generated by Django 3.1.5 on 2021-01-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0014_auto_20210130_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ratings',
            field=models.ManyToManyField(blank=True, null=True, to='hireapp.Rating'),
        ),
    ]
