# Generated by Django 3.1.5 on 2021-01-30 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0015_auto_20210130_0530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
