# Generated by Django 3.1.5 on 2021-01-30 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0016_delete_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='hireapp.job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('P', 'Applied'), ('C', 'Considering'), ('A', 'Accepted'), ('D', 'Decline')], default='P', max_length=1),
        ),
    ]
