# Generated by Django 3.1.5 on 2021-01-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0017_auto_20210130_0613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applications',
            new_name='Application',
        ),
    ]
