# Generated by Django 3.1.5 on 2021-01-30 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0018_auto_20210130_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='hireapp.employee'),
            preserve_default=False,
        ),
    ]
